'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.web_service_alumnoSoap")>  _
    Public Interface web_service_alumnoSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getDataAlumno", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getDataAlumno() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getDataAlumno", ReplyAction:="*")>  _
        Function getDataAlumnoAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface web_service_alumnoSoapChannel
        Inherits ServiceReference1.web_service_alumnoSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class web_service_alumnoSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.web_service_alumnoSoap)
        Implements ServiceReference1.web_service_alumnoSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function getDataAlumno() As System.Data.DataSet Implements ServiceReference1.web_service_alumnoSoap.getDataAlumno
            Return MyBase.Channel.getDataAlumno
        End Function
        
        Public Function getDataAlumnoAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReference1.web_service_alumnoSoap.getDataAlumnoAsync
            Return MyBase.Channel.getDataAlumnoAsync
        End Function
    End Class
End Namespace
